apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: task01
  namespace: poc-ns
spec:
  schedulerName: volcano
  policies:
  - event: PodEvicted
    action: RestartJob
  maxRetry: 2
  plugins:
    env: []
  tasks:
  - name: "apps"
    replicas: 3
    policies:
    - event: TaskCompleted
      action: CompleteJob
    template:
      spec:
        # tolerations:
        # - key: node.kubernetes.io/os
        #   operator: Equal
        #   value: windows
        #   effect: NoSchedule
        containers:
        - name: main
          image: gcr.io/<project-id>/sample-apps:linux-v1
          env:
          - name: INPUT_BUCKET
            value: "<your-bucket>"
          - name: INPUT_FILE
            value: "users/001/input.csv"
          - name: PARAMETER_FILE
            value: "users/001/parameters.csv"
        restartPolicy: OnFailure
        serviceAccountName: ksa-poc
